version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - TZ=Europe/Madrid
      - TEMPLATE_AGENT=1
      - TEMPLATE_TEMPLATES=https://raw.githubusercontent.com/alexcaraballo/LDDS/main/templates.json

volumes:
  portainer_data:

