version: '3.8'

services:
  ubuntu_container:
    image: darkvus/ubuntu-ssh:latest
    container_name: ${CONTAINER_NAME}
    environment:
      - TZ=UTC
      - DEBIAN_FRONTEND=noninteractive
    command: tail -f /dev/null
    ports:
      - "8000:8000"
    restart: always
