version: '3'

services:
  ubuntu_container:
    image: ubuntu:latest
    container_name: ubuntu_container
    volumes:
      - ./dependencies.sh:/install.sh
    command:
      - /bin/sh
      - -c
      - |
        ls -la
        ls -la install.sh