version: '3'

services:
  ubuntu_container:
    image: ubuntu:latest
    container_name: ubuntu_container
    environment:
      - TZ=UTC
      - DEBIAN_FRONTEND=noninteractive
    command:
      - /bin/bash
      - -c
      - |
        apt-get update
        apt-get install curl -y
        curl https://raw.githubusercontent.com/alexcaraballo/LDDS/main/stacks/ubuntu/dependencies.sh -o dependencies.sh
        chmod +x dependencies.sh
        ./dependencies.sh