version: '3'

services:
  ubuntu_container:
    image: ubuntu:latest
    container_name: ubuntu_container
    volumes:
      - ./dependencies.sh:/install.sh
    command: /bin/bash -c "chmod +x /install.sh && /install.sh"